model:
  primary: "oai_4o_latest"           # String for the main LLM model to use
  allow_image_input: true    # Boolean to enable image inputs into the model

graph_verification:
  enabled: true              # Boolean to enable graph verification
  method: "llm"              # Options: "llm" (requires model) or "bert"
  llm_model: "oai_4o_latest"         # Only used if method is "llm"

prompt_mode:
  mode: "original"         # Options: "original", "elaborated", "q_learning", "q_training"
  elaborator_model: "oai_4o_latest"  # String for the LLM model to use for prompt elaboration

text_summariser:
  model: "oai_4o_latest"     # String for the LLM model to use for text summarization

embedding:
  method: "aws"        # Options: "langchain", "clip", or "aws"
  model: "amazon.titan-embed-image-v1"     # Required if method is "langchain" or "aws"

logger:
  level: "INFO"              # Options: "DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"