document_range:
  document_ids: []
  enabled: false
embedding:
  method: aws
  model: amazon.titan-embed-image-v1
graph_verification:
  enabled: true
  llm_model: oai_4o_latest
  method: bert
iteration:
  loop_retries: 5
  pass_threshold: 0
logger:
  level: DEBUG
model:
  allow_image_input: true
  primary: oai_4o_latest
prompt_mode:
  elaborator_model: oai_4o_latest
  mode: original
rag:
  text_similarity_threshold: 0.55
text_summariser:
  model: oai_4o_latest
